package com.example.saso.entity;

import java.io.Serializable;
import java.util.Date;

public class Order implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated Thu Aug 01 17:06:48 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.cate_select
     *
     * @mbg.generated Thu Aug 01 17:06:48 CST 2024
     */
    private String cateSelect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.nece_title
     *
     * @mbg.generated Thu Aug 01 17:06:48 CST 2024
     */
    private String neceTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.nece_detail
     *
     * @mbg.generated Thu Aug 01 17:06:48 CST 2024
     */
    private String neceDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.deadline
     *
     * @mbg.generated Thu Aug 01 17:06:48 CST 2024
     */
    private Date deadline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.phone
     *
     * @mbg.generated Thu Aug 01 17:06:48 CST 2024
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.reward
     *
     * @mbg.generated Thu Aug 01 17:06:48 CST 2024
     */
    private Integer reward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order
     *
     * @mbg.generated Thu Aug 01 17:06:48 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbg.generated Thu Aug 01 17:06:48 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbg.generated Thu Aug 01 17:06:48 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.cate_select
     *
     * @return the value of order.cate_select
     *
     * @mbg.generated Thu Aug 01 17:06:48 CST 2024
     */
    public String getCateSelect() {
        return cateSelect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.cate_select
     *
     * @param cateSelect the value for order.cate_select
     *
     * @mbg.generated Thu Aug 01 17:06:48 CST 2024
     */
    public void setCateSelect(String cateSelect) {
        this.cateSelect = cateSelect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.nece_title
     *
     * @return the value of order.nece_title
     *
     * @mbg.generated Thu Aug 01 17:06:48 CST 2024
     */
    public String getNeceTitle() {
        return neceTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.nece_title
     *
     * @param neceTitle the value for order.nece_title
     *
     * @mbg.generated Thu Aug 01 17:06:48 CST 2024
     */
    public void setNeceTitle(String neceTitle) {
        this.neceTitle = neceTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.nece_detail
     *
     * @return the value of order.nece_detail
     *
     * @mbg.generated Thu Aug 01 17:06:48 CST 2024
     */
    public String getNeceDetail() {
        return neceDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.nece_detail
     *
     * @param neceDetail the value for order.nece_detail
     *
     * @mbg.generated Thu Aug 01 17:06:48 CST 2024
     */
    public void setNeceDetail(String neceDetail) {
        this.neceDetail = neceDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.deadline
     *
     * @return the value of order.deadline
     *
     * @mbg.generated Thu Aug 01 17:06:48 CST 2024
     */
    public Date getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.deadline
     *
     * @param deadline the value for order.deadline
     *
     * @mbg.generated Thu Aug 01 17:06:48 CST 2024
     */
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.phone
     *
     * @return the value of order.phone
     *
     * @mbg.generated Thu Aug 01 17:06:48 CST 2024
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.phone
     *
     * @param phone the value for order.phone
     *
     * @mbg.generated Thu Aug 01 17:06:48 CST 2024
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.reward
     *
     * @return the value of order.reward
     *
     * @mbg.generated Thu Aug 01 17:06:48 CST 2024
     */
    public Integer getReward() {
        return reward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.reward
     *
     * @param reward the value for order.reward
     *
     * @mbg.generated Thu Aug 01 17:06:48 CST 2024
     */
    public void setReward(Integer reward) {
        this.reward = reward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Thu Aug 01 17:06:48 CST 2024
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cateSelect=").append(cateSelect);
        sb.append(", neceTitle=").append(neceTitle);
        sb.append(", neceDetail=").append(neceDetail);
        sb.append(", deadline=").append(deadline);
        sb.append(", phone=").append(phone);
        sb.append(", reward=").append(reward);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}