package com.example.saso.mapper;

import com.example.saso.entity.ServiceCategory;
import com.example.saso.entity.ServiceCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServiceCategoryMapper {
    List<ServiceCategory> list();
    List<Integer> test();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_category
     *
     * @mbg.generated Mon Jul 22 15:28:55 CST 2024
     */
    long countByExample(ServiceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_category
     *
     * @mbg.generated Mon Jul 22 15:28:55 CST 2024
     */
    int deleteByExample(ServiceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_category
     *
     * @mbg.generated Mon Jul 22 15:28:55 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_category
     *
     * @mbg.generated Mon Jul 22 15:28:55 CST 2024
     */
    int insert(ServiceCategory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_category
     *
     * @mbg.generated Mon Jul 22 15:28:55 CST 2024
     */
    int insertSelective(ServiceCategory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_category
     *
     * @mbg.generated Mon Jul 22 15:28:55 CST 2024
     */
    List<ServiceCategory> selectByExample(ServiceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_category
     *
     * @mbg.generated Mon Jul 22 15:28:55 CST 2024
     */
    ServiceCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_category
     *
     * @mbg.generated Mon Jul 22 15:28:55 CST 2024
     */
    int updateByExampleSelective(@Param("row") ServiceCategory row, @Param("example") ServiceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_category
     *
     * @mbg.generated Mon Jul 22 15:28:55 CST 2024
     */
    int updateByExample(@Param("row") ServiceCategory row, @Param("example") ServiceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_category
     *
     * @mbg.generated Mon Jul 22 15:28:55 CST 2024
     */
    int updateByPrimaryKeySelective(ServiceCategory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_category
     *
     * @mbg.generated Mon Jul 22 15:28:55 CST 2024
     */
    int updateByPrimaryKey(ServiceCategory row);
}